CREATE OR REPLACE PROCEDURE benutzer_anlegen
( username IN VARCHAR2,
  vorname  IN VARCHAR2,
  nachname IN VARCHAR2,
  passwort IN VARCHAR2,
  gruppe   IN VARCHAR2 )
  
IS

DECLARE

     tmpVar1   VARCHAR2(100);
     

BEGIN

INSERT INTO BENUTZER
(US_VORNAME, US_NACHNAME, US_USERNAME, US_PASSWORD)
VALUES
(:P2_TEXT_FIELD2,:P2_TEXT_FIELD3, :P2_TEXT_FIELD1, :P2_TEXT_FIELD3);

commit;

INSERT INTO US_USGR
( BENUTZER_US_PK_NR, BENUTZER_GRUPPE_USGR_PK_NR )
VALUES
( (select us.US_PK_NR from BENUTZER us where us.US_USERNAME = ':P2_TEXT_FIELD2'), 
  (select usgr.USGR_PK_NR from BENUTZER_GRUPPE usgr where usgr.USGR_NAME = ':P2_SELECT_GROUP')
);

end;